import ClientLayout from "./ClientLayout";
import { Sora } from "next/font/google";
import "./globals.css";
import { Toaster} from "@/components/ui/sonner";

const sora = Sora({
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Panel -Custom Pack Boxes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
        <Toaster/>
      </body>
    </html>
  );
}
